### PR TITLE
Merged master with Lgm_SummersDiffCoeff tweaks

### PR DESCRIPTION
**Pull request by JeffreyBroll**
Looks like this was all I had to do to get everything happy on Chicoma.  Next I'll look at Roci in case that got weird.

### CODE REVIEW

**Comment by drsteve** [comment]
Thanks,
That's #45 and #49... Compilation is still failing because of #48. Relevant compiler complaints below.
```
Lgm_SummersDiffCoeff.c:2861:32: error: incompatible function pointer types passing 'double (double, struct localDiffusionCoefficientAtSpecificThetaGlauertAndHorneFunctionParams *)' to parameter of type 'double (*)(double, _qpInfo *)' (aka 'double (*)(double, int *)') [-Wincompatible-function-pointer-types]
                                        j = Lgm_SimpleRiemannSum( localDiffusionCoefficientAtSpecificThetaGlauertAndHorneWeightedByTanTheta,(_qpInfo *) &p2,(double) tempxmin,(double) tempxmax, &tempDaa, (int) 0);
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lgm_SummersDiffCoeff.c:20:36: note: passing argument to parameter 'f' here
int Lgm_SimpleRiemannSum( double (*f)( double, _qpInfo * ), _qpInfo *qpInfo, double xleft, double xright, double *result, int VerbosityLevel );
                                   ^
Lgm_SummersDiffCoeff.c:2866:31: error: incompatible function pointer types passing 'double (double, struct localDiffusionCoefficientAtSpecificThetaGlauertAndHorneFunctionParams *)' to parameter of type 'double (*)(double, _qpInfo *)' (aka 'double (*)(double, int *)') [-Wincompatible-function-pointer-types]
                                j = Lgm_SimpleRiemannSum( localDiffusionCoefficientAtSpecificThetaGlauertAndHorneWeightedByTanTheta, (_qpInfo *) &p2,(double) xmin,(double) xmax, &tempDaa, (int) 0);
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by drsteve** [comment]
I've pulled the casting from this PR (for #49) and my other fixes, including a fix for the issue in my last comment here, into #51. If you can take a quick look over that I'd appreciate it.

**Comment by drsteve** [comment]
Closing as a superset of fixes was included in #51
