### PR TITLE
PR #67 amended to retain praxis

### PR DESCRIPTION
**Pull request by JeffreyBroll**
A few familiar problems popped up when I ran a fresh build with GCC 16.1.1 and "--coverage -g" so I had to bonk a few things back into place

- some familiar incomplete function prototypes, but now Lgm_SummersDxxThings don't fuss about incompatible types
- some char* vs char*[] type whining
- praxis decobwebbed and properly headed

### CODE REVIEW

File: libLanlGeoMag/Lgm_QuadPack.c [hunk 1]
```diff
@@ -3,27 +3,13 @@
...
-double  (*f)( double, _qpInfo *); /*  The integrand function -- I.e. the function to integrate    	 */
-_qpInfo *qpInfo;        	  /*  Auxilliary information to pass to function (to avoid making globals) */
-double   a;             	  /*  Lower Limit of integration.                                 	 */
-double   b;             	  /*  Upper limit of integration.                                 	 */
-double   epsabs;        	  /*  Absolute accuracy requested.                                	 */
-double   epsrel;        	  /*  Relative accuracy requested.                                	 */
-double  *result;        	  /*  The desired result. I.e. integral of f() from a to b        	 */
-double  *abserr;        	  /*  Estimate of the modulus of the absolute error in the result 	 */
-int     *neval;         	  /*  The number of integrand evaluations performed.              	 */
-int     *ier;           	  /*  Error flag. An error occurred if ier > 0. See below.        	 */
```
Comment (drsteve) [inline libLanlGeoMag/Lgm_QuadPack.c:16]: We need to preserve the comments somewhere. Doxygen docstring?

File: libLanlGeoMag/Lgm_QuadPack.c [hunk 2]
```diff
@@ -248,34 +234,13 @@ int TMPiwork[600];
...
-_qpInfo *qpInfo;                  /*  Auxilliary information to pass to function (to avoid making globals) */
-double   a;             	  /*  Lower Limit of integration.                                 */
-double   b;             	  /*  Upper limit of integration.                                 */
-double   epsabs;        	  /*  Absolute accuracy requested.                                */
-double   epsrel;        	  /*  Relative accuracy requested.                                */
-int      limit;
-double  *result;        	  /*  The desired result. I.e. integral of f() from a to b        */
-double  *abserr;        	  /*  Estimate of the modulus of the absolute error in the result */
-int     *neval;         	  /*  The number of integrand evaluations performed.              */
-int     *ier;           	  /*  Error flag. An error occurred if ier > 0. See below.        */
```
Comment (drsteve) [inline libLanlGeoMag/Lgm_QuadPack.c:268]: Again, comments need preserving. Doxygen docstring seems like a good spot.

File: libLanlGeoMag/Lgm_QuadPack.c [hunk 3]
```diff
@@ -1125,26 +1086,11 @@ int dqelg(int n, double epstab[], double *result, double *abserr, double res3la[
...
 /*
  *      QUADPACK DQK21 Routine converted to C
  */
-int dqk21(f, qpInfo, a, b, result, abserr, resabs, resasc)
-double  (*f)( double, _qpInfo *); /*  The integrand function -- I.e. the function to integrate           */
-_qpInfo *qpInfo;                  /*  Auxilliary information to pass to function (to avoid making globals) */
-double   a;             	  /*  Lower Limit of integration.                                 */
-double   b;             	  /*  Upper limit of integration.                                 */
-double  *result;        	  /*  The desired result. I.e. integral of f() from a to b        */
-double  *abserr;        	  /*  Estimate of the modulus of the absolute error in the result */
```
Comment (drsteve) [inline libLanlGeoMag/Lgm_QuadPack.c:1141]: And one more on comments to be preserved

File: libLanlGeoMag/Lgm_QuadPack3.c [hunk 4]
```diff
@@ -3,28 +3,13 @@
...
-double   a;             	  /*  Lower Limit of integration.                                 	 */
-double   b;             	  /*  Upper limit of integration.                                 	 */
-int      npts2;
-double   *points;
-double   epsabs;        	  /*  Absolute accuracy requested.                                	 */
-double   epsrel;        	  /*  Relative accuracy requested.                                	 */
-double  *result;        	  /*  The desired result. I.e. integral of f() from a to b        	 */
-double  *abserr;        	  /*  Estimate of the modulus of the absolute error in the result 	 */
-int     *neval;         	  /*  The number of integrand evaluations performed.              	 */
-int     *ier;           	  /*  Error flag. An error occurred if ier > 0. See below.        	 */
```
Comment (drsteve) [inline libLanlGeoMag/Lgm_QuadPack3.c:18]: Comments need preserving. Maybe doxygen docstring?

File: libLanlGeoMag/Lgm_QuadPack3.c [hunk 5]
```diff
@@ -292,32 +277,14 @@ int	    verbosity;
...
-int      npts2;
-double  *points;
-double   epsabs;        	  /*  Absolute accuracy requested.                                */
-double   epsrel;        	  /*  Relative accuracy requested.                                */
-int      limit;
-double  *result;        	  /*  The desired result. I.e. integral of f() from a to b        */
-double  *abserr;        	  /*  Estimate of the modulus of the absolute error in the result */
-int     *neval;         	  /*  The number of integrand evaluations performed.              */
-int     *ier;           	  /*  Error flag. An error occurred if ier > 0. See below.        */
-double   *alist;
```
Comment (drsteve) [inline libLanlGeoMag/Lgm_QuadPack3.c:309]: Comment preservation society.

File: libLanlGeoMag/praxis.c [hunk 6]
```diff
@@ -19,1021 +19,781 @@
...
+  nf = 1;
+  out[3] = qf1 = fx = (*funct)(x, data);
+  abstol = t2 = small + fabs(abstol);
+  dmin = small;
+  if (h < abstol * 100.0)
+    h = abstol * 100;
+  ldt = h;
+  inimat(1, n, 1, n, v, 0.0);
+  for (i = 1; i <= n; i++)
+    v[i][i] = 1.0;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c:102]: Can this get some braces for clarity?

File: libLanlGeoMag/praxis.c [hunk 7]
```diff
@@ -19,1021 +19,781 @@
...
+  m4 = sqrt(m2);
+  srand(1);
+  ldfac = (illc ? 0.1 : 0.01);
+  kt = nl = 0;
+  nf = 1;
+  out[3] = qf1 = fx = (*funct)(x, data);
+  abstol = t2 = small + fabs(abstol);
+  dmin = small;
+  if (h < abstol * 100.0)
+    h = abstol * 100;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c:97]: Can this get some braces for clarity?

File: libLanlGeoMag/praxis.c [hunk 8]
```diff
@@ -19,1021 +19,781 @@
...
+  while (1) {
+    sf = d[1];
+    d[1] = s = 0.0;
+    praxismin(1, 2, &(d[1]), &s, &fx, 0, n, x, v, &qa, &qb, &qc, qd0, qd1, q0,
+              q1, &nf, &nl, &fx, m2, m4, dmin, ldt, reltol, abstol, small, h,
+              funct, data);
+    if (s <= 0.0)
+      mulcol(1, n, 1, 1, v, v, -1.0);
+    if (sf <= 0.9 * d[1] || 0.9 * sf >= d[1])
+      inivec(2, n, d, 0.0);
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would be helpful

File: libLanlGeoMag/praxis.c [hunk 9]
```diff
@@ -19,1021 +19,781 @@
...
+          s = illc ? d[k2] * (s + z[k2]) * (s + z[k2]) : sl - fx;
+          if (df < s) {
+            df = s;
+            kl = k2;
+          }
+        }
+        if (!illc && df < fabs(100.0 * macheps * fx))
+          illc = 1;
+        else
+          break;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 10]
```diff
@@ -19,1021 +19,781 @@
...
+        sl = x[i];
+        x[i] = y[i];
+        y[i] = sl -= y[i];
+        lds += sl * sl;
+      }
+      lds = sqrt(lds);
+      if (lds > small) {
+        for (i = kl - 1; i >= k; i--) {
+          for (j = 1; j <= n; j++)
+            v[j][i + 1] = v[j][i];
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 11]
```diff
@@ -19,1021 +19,781 @@
...
+                  q0, q1, &nf, &nl, &fx, m2, m4, dmin, ldt, reltol, abstol,
+                  small, h, funct, data);
+        if (lds <= 0.0) {
+          lds = -lds;
+          mulcol(1, n, k, k, v, v, -1.0);
+        }
+      }
+      ldt *= ldfac;
+      if (ldt < lds)
+        ldt = lds;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 12]
```diff
@@ -19,1021 +19,781 @@
...
+      t2 = m2 * sqrt(vecvec(1, n, 0, x, x)) + abstol;
+      kt = (ldt > 0.5 * t2) ? 0 : kt + 1;
+      if (kt > ktm) {
+        out[1] = 0.0;
+        emergency = 1;
+      }
+    }
+    if (emergency)
+      break;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 13]
```diff
@@ -19,1021 +19,781 @@
...
+      s = q0[i];
+      q0[i] = x[i];
+      x[i] = qa * s + qb * x[i] + qc * q1[i];
+    }
+    /* end of quad */
+    dn = 0.0;
+    for (i = 1; i <= n; i++) {
+      d[i] = 1.0 / sqrt(d[i]);
+      if (dn < d[i])
+        dn = d[i];
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 14]
```diff
@@ -19,1021 +19,781 @@
...
+      mulcol(1, n, j, j, v, v, s);
+    }
+    if (scbd > 1.0) {
+      s = vlarge;
+      for (i = 1; i <= n; i++) {
+        sl = z[i] = sqrt(mattam(1, n, i, i, v, v));
+        if (sl < m4)
+          z[i] = m4;
+        if (s > sl)
+          s = sl;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 15]
```diff
@@ -19,1021 +19,781 @@
...
+        z[i] = 1.0 / sl;
+        if (z[i] > scbd) {
+          sl = 1.0 / scbd;
+          z[i] = scbd;
+        }
+        mulrow(1, n, i, i, v, v, sl);
+      }
+    }
+    for (i = 1; i <= n; i++)
+      ichrowcol(i + 1, n, i, i, v);
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 16]
```diff
@@ -19,1021 +19,781 @@
...
+    em[0] = em[2] = macheps;
+    em[4] = 10 * n;
+    em[6] = vsmall;
+    dupmat(1, n, 1, n, a, v);
+    if (qrisngvaldec(a, n, n, d, v, em) != 0) {
+      out[1] = 2.0;
+      emergency = 1;
+    }
+    if (emergency)
+      break;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 17]
```diff
@@ -19,1021 +19,781 @@
...
+    if (scbd > 1.0) {
+      for (i = 1; i <= n; i++)
+        mulrow(1, n, i, i, v, v, z[i]);
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 18]
```diff
@@ -19,1021 +19,781 @@
...
+    }
+    /* sort */
+    for (i = 1; i <= n - 1; i++) {
+      k = i;
+      s = d[i];
+      for (j = i + 1; j <= n; j++)
+        if (d[j] > s) {
+          k = j;
+          s = d[j];
+        }
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility. (I think the selection matches the block, but I'm honestly not sure at first glance)

File: libLanlGeoMag/praxis.c [hunk 19]
```diff
@@ -19,1021 +19,781 @@
...
+          s = v[j][i];
+          v[j][i] = v[j][k];
+          v[j][k] = s;
+        }
+      }
+    }
+    /* end of sort */
+    dmin = d[n];
+    if (dmin < small)
+      dmin = small;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 20]
```diff
@@ -19,1021 +19,781 @@
...
+  dz = *d2 < reltol;
+  s = sqrt(vecvec(1, n, 0, x, x));
+  t2 = m4 * sqrt(fabs(*fx) / (dz ? dmin : *d2) + s * ldt) + m2 * ldt;
+  s = s * m4 + abstol;
+  if (dz && (t2 > s))
+    t2 = s;
+  if (t2 < small)
+    t2 = small;
+  if (t2 > 0.01 * h)
+    t2 = 0.01 * h;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 21]
```diff
@@ -19,1021 +19,781 @@
...
+      }
+      *d2 =
+          (x2 * ((*f1) - f0) - (*x1) * (f2 - f0)) / ((*x1) * x2 * ((*x1) - x2));
+    }
+    /* estimate first derivative at 0 */
+    d1 = ((*f1) - f0) / (*x1) - (*x1) * (*d2);
+    dz = 1;
+    x2 = (*d2 <= small) ? ((d1 < 0.0) ? h : -h) : -0.5 * d1 / (*d2);
+    if (fabs(x2) > h)
+      x2 = (x2 > 0.0) ? h : -h;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 22]
```diff
@@ -19,1021 +19,781 @@
...
+    while (1) {
+      f2 = praxisflin(x2, j, n, x, v, qa, qb, qc, qd0, qd1, q0, q1, nf, funct,
+                      data);
+      if (k < nits && f2 > f0) {
+        k++;
+        if (f0 < *f1 && (*x1) * x2 > 0.0)
+          break;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 23]
```diff
@@ -19,1021 +19,781 @@
...
+        loop = 0;
+        break;
+      }
+    }
+  }
+  (*nl)++;
+  if (f2 > fm)
+    x2 = xm;
+  else
+    fm = f2;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 24]
```diff
@@ -19,1021 +19,781 @@
...
+  *d2 = (fabs(x2 * (x2 - (*x1))) > small)
+            ? ((x2 * ((*f1) - f0) - (*x1) * (fm - f0)) /
+               ((*x1) * x2 * ((*x1) - x2)))
+            : ((k > 0) ? 0.0 : *d2);
+  if (*d2 <= small)
+    *d2 = small;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 25]
```diff
@@ -19,1021 +19,781 @@
...
-int 	l;
-int 	u;
-int 	j;
-double 	**a;
-double 	b[];
-{
-	for (; l<=u; l++) a[l][j]=b[l];
+void dupcolvec(int l, int u, int j, double **a, double *b) {
+  for (; l <= u; l++)
+    a[l][j] = b[l];
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 26]
```diff
@@ -19,1021 +19,781 @@
...
-double 	**b;
-{
-	int k;
-
-	for (; l<=u; l++)
-		for (k=i; k<=j; k++) a[l][k]=b[l][k];
+void dupmat(int l, int u, int i, int j, double **a, double **b) {
+  for (; l <= u; l++)
+    for (int k = i; k <= j; k++)
+      a[l][k] = b[l][k];
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 27]
```diff
@@ -19,1021 +19,781 @@
...
-int u;
-int i;
-double a[];
-double **b;
-double x;
-{
-	for (; l<=u; l++) a[l] += b[l][i]*x;
+void elmveccol(int l, int u, int i, double *a, double **b, double x) {
+  for (; l <= u; l++)
+    a[l] += b[l][i] * x;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 28]
```diff
@@ -19,1021 +19,781 @@
...
-double **a;
-double x;
-{
-	int j;
-
-	for (; lr<=ur; lr++)
-		for (j=lc; j<=uc; j++) a[lr][j]=x;
+  for (; lr <= ur; lr++)
+    for (j = lc; j <= uc; j++)
+      a[lr][j] = x;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 29]
```diff
@@ -19,1021 +19,781 @@
...
-void inivec(l, u, a, x)
-int l;
-int u;
-double a[];
-double x;
-{
-	for (; l<=u; l++) a[l]=x;
+void inivec(int l, int u, double *a, double x) {
+  for (; l <= u; l++)
+    a[l] = x;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 30]
```diff
@@ -19,1021 +19,781 @@
...
-int i;
-int j;
-double **a;
-double **b;
-double x;
-{
-	for (; l<=u; l++) a[l][i]=b[l][j]*x;
+void mulcol(int l, int u, int i, int j, double **a, double **b, double x) {
+  for (; l <= u; l++)
+    a[l][i] = b[l][j] * x;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 31]
```diff
@@ -19,1021 +19,781 @@
...
-int i;
-int j;
-double **a;
-double **b;
-double x;
-{
-	for (; l<=u; l++) a[i][l]=b[j][l]*x;
+void mulrow(int l, int u, int i, int j, double **a, double **b, double x) {
+  for (; l <= u; l++)
+    a[i][l] = b[j][l] * x;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 32]
```diff
@@ -19,1021 +19,781 @@
...
+      if (fabs(b[k]) >= tol) {
+        if (fabs(d[k]) < tol) {
+          c = 0.0;
+          s = 1.0;
+          for (i = k; i <= n1; i++) {
+            f = s * b[i];
+            b[i] *= c;
+            i1 = i + 1;
+            if (fabs(f) < tol)
+              break;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 33]
```diff
@@ -19,1021 +19,781 @@
...
+            d[i1] = h = sqrt(f * f + g * g);
+            c = g / h;
+            s = -f / h;
+            rotcol(1, m, k, i1, u, c, s);
+          }
+          break;
+        }
+      } else {
+        if (fabs(b[k]) > bmax)
+          bmax = fabs(b[k]);
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 34]
```diff
@@ -19,1021 +19,781 @@
...
+        break;
+      }
+    }
+    if (k == n1) {
+      if (d[n] < 0.0) {
+        d[n] = -d[n];
+        for (i = 1; i <= n0; i++)
+          v[i][n] = -v[i][n];
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 35]
```diff
@@ -19,1021 +19,781 @@
...
+      }
+      if (d[n] <= min)
+        rnk--;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 36]
```diff
@@ -19,1021 +19,781 @@
...
+      n = n1;
+    } else {
+      count++;
+      if (count > max)
+        break;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 37]
```diff
@@ -19,1021 +19,781 @@
...
+        i1 = i - 1;
+        g = b[i1];
+        y = d[i];
+        h = s * g;
+        g *= c;
+        z = sqrt(f * f + h * h);
+        c = f / z;
+        s = h / z;
+        if (i1 != k1)
+          b[i1 - 1] = z;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 38]
```diff
@@ -19,1021 +19,781 @@
...
-    p = (double *)malloc((unsigned) (u-l+1)*sizeof(double));
-    if (!p) {
-	fprintf(stderr, "Memory allocation failure in allocate_real_vector\n");
-	exit(1);
-    }
-
-    return(p-l);
+void free_real_matrix(double **m, int lr, int ur, int lc) {
+  for (int i = ur; i >= lr; i--)
+    free((char *)(m[i] + lc));
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 39]
```diff
@@ -19,1021 +19,781 @@
...
+
+  i1 = n;
+  v[n][n] = 1.0;
+  for (i = n - 1; i >= 1; i--) {
+    h = b[i] * a[i][i1];
+    if (h < 0.0) {
+      for (j = i1; j <= n; j++)
+        v[j][i] = a[i][j] / h;
+      for (j = i1; j <= n; j++)
+        elmcol(i1, n, j, i, v, v, matmat(i1, n, i, j, a, v));
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 40]
```diff
@@ -19,1021 +19,781 @@
...
+    }
+    for (j = i1; j <= n; j++)
+      v[i][j] = v[j][i] = 0.0;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

File: libLanlGeoMag/praxis.c [hunk 41]
```diff
@@ -19,1021 +19,781 @@
...
-	for (; l<=u; l++) a[i][l] += b[j][l]*x;
+void elmcol(int l, int u, int i, int j, double **a, double **b, double x) {
+  for (; l <= u; l++) {
+    a[l][i] += b[l][j] * x;
+  }
 }
 
+void elmrow(int l, int u, int i, int j, double **a, double **b, double x) {
+  for (; l <= u; l++)
+    a[i][l] += b[j][l] * x;
```
Comment (drsteve) [inline libLanlGeoMag/praxis.c]: Braces would help legibility

**Review by drsteve — CHANGES_REQUESTED** [review]

**Comment by JeffreyBroll** [comment]
Commit 29e8b3ab put the parameter descriptions into Doxygen-read comments in Lgm_QuadPack.h and commit 8998a857 puts brackets into praxis.  I'm not entirely clear on what's happening in the three QuadPack#.c files so I didn't mess with those yet.
